import { EdgeStoreProvider } from "@/lib/edgestore";

export const metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
    <main className="text-black w-full">
      <EdgeStoreProvider>{children}</EdgeStoreProvider>
    </main>
  );
}
